# Generated by Django 2.1.5 on 2019-03-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190221_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebrity',
            options={'verbose_name': 'Celebrity', 'verbose_name_plural': 'Celebrities'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='celebrity',
        ),
        migrations.AddField(
            model_name='movie',
            name='celebrities',
            field=models.ManyToManyField(to='movies.Celebrity'),
        ),
    ]
