# Generated by Django 2.1.5 on 2019-02-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='name',
        ),
        migrations.AddField(
            model_name='director',
            name='first_name',
            field=models.CharField(default='Prakaj', max_length=15),
        ),
        migrations.AddField(
            model_name='director',
            name='last_name',
            field=models.CharField(default='Prakaj', max_length=15),
        ),
    ]
